### ISSUE TITLE
make Error 1

### ISSUE THREAD

**Issue by ezamp** [appfruits/buildroot-boards#1]
Hi, I found the following error when I tried to compile with the make command:

> > > linux linux-3.10-at91 Extracting
> > > gzip -d -c /home/emanuele/Desktop/Buildroot/buildroot/dl/linux-linux-3.10-at91.tar.gz | tar --strip-components=1 -C /home/emanuele/Desktop/Buildroot/buildroot/output/build/linux-linux-3.10-at91  -xf -
> > > linux linux-3.10-at91 Patching
> > > for p in ../boards/board/acmesystems/acqua/patches/kernel/24bpp_for_5_and_7_inch_lcd.patch ; do if test -d $p ; then support/scripts/apply-patches.sh  /home/emanuele/Desktop/Buildroot/buildroot/output/build/linux-linux-3.10-at91 $p linux-*.patch || exit 1 ; else support/scripts/apply-patches.sh  /home/emanuele/Desktop/Buildroot/buildroot/output/build/linux-linux-3.10-at91 `dirname $p` `basename $p` || exit 1; fi done
> > > Aborting.  '../boards/board/acmesystems/acqua/patches/kernel' is not a directory.
> > > package/pkg-generic.mk:147: recipe for target '/home/emanuele/Desktop/Buildroot/buildroot/output/build/linux-linux-3.10-at91/.stamp_patched' failed
> > > make: **\* [/home/emanuele/Desktop/Buildroot/buildroot/output/build/linux-linux-3.10-at91/.stamp_patched] Error 1

I run the information in the file readme.md and I used the standard options described in the guide.

Thank You

Emanuele

**Comment by pschuster** [comment]
Hi,

can you please show your folder structure? The script complains that it does not find ../boards/board/acmesystems/acqua/patches/kernel which is ok, as the folder should be buildroot-boards/board/acmesystems/acqua/patches/kernel. I am not sure if your folder structure got messed up during the process or if the folder is not correctly set in one of the config files.

As far as I remember the folder is set with BR2_EXTERNAL which is set in one of the first steps in the guide. Did you do that?

**Comment by ezamp** [comment]
Hi,

yes, I configured BR2_EXTERNAL with the command: make BR2_EXTERNAL=../buildroot-boards acqua_defconfig

The folder structure is:
-buildroot
-buildroot-boards
---board
------acmesystems
---------acqua
------------patches
---------------kernel
------------rootfs-overlay
--------------- ...
---configs
---packages

Thank you for your help

**Comment by ezamp** [comment]
Hi,

I think the error is in the line 340:
BR2_LINUX_KERNEL_PATCH="../boards/board/acmesystems/acqua/patches/kernel/24bpp_for_5_and_7_inch_lcd.patch"

here the path is wrong, I correct in this way:
BR2_LINUX_KERNEL_PATCH="../buildroot-boards/board/acmesystems/acqua/patches/kernel/24bpp_for_5_and_7_inch_lcd.patch"

the same thing I did in the line 343... Now the compilation ends successfully

Emanuele

**Comment by pschuster** [comment]
Lol. A second ago I found the same error. In this second I am fixing it. In a minute I will commit a new aqua_defconfig. Would you mind to have a look if my changes reflect yours?

Thanks.
Phillip

**Comment by ezamp** [comment]
yes, I corrected in the same way

Emanuele

**Comment by pschuster** [comment]
Please let me know if you have problems again. It would be great to here if everything works or other things should be fixed. I think our work will help other users.

Thanks. 
Phillip
